In [1]:
# pandas iss a library in python used for working with data sets.
#it has functions for analysing,cleaning,exploring and manipulating data.
# the name panda has a reference to both panel data and python data analysis.

In [7]:
import pandas as pd
import numpy as np

In [8]:
ls     ##linex command contain all directory

 Volume in drive C is Windows-SSD
 Volume Serial Number is F245-89E4

 Directory of C:\Users\DEEPIKA SHERAWAT


 Directory of C:\Users\DEEPIKA SHERAWAT


 Directory of C:\Users\DEEPIKA SHERAWAT


 Directory of C:\Users\DEEPIKA SHERAWAT


 Directory of C:\Users\DEEPIKA SHERAWAT



File Not Found


In [9]:
df=pd.read_csv("mtcars.csv")

In [10]:
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [11]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [15]:
#data=df.to_numpy() covert dataframe in array

In [14]:
#data

In [9]:
df.shape

(32, 11)

In [10]:
df.tail()

mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
27  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [11]:
df.sample(5)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [12]:
df.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [13]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [14]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64  
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64  
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64  
 8   am      32 non-null     int64  
 9   gear    32 non-null     int64  
 10  carb    32 non-null     int64  
dtypes: float64(5), int64(6)
memory usage: 2.9 KB


In [16]:
df.isna()

mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear  \
0   False  False  False  False  False  False  False  False  False  False   
1   False  False  False  False  False  False  False  False  False  False   
2   False  False  False  False  False  False  False  False  False  False   
3   False  False  False  False  False  False  False  False  False  False   
4   False  False  False  False  False  False  False  False  False  False   
5   False  False  False  False  False  False  False  False  False  False   
6   False  False  False  False  False  False  False  False  False  False   
7   False  False  False  False  False  False  False  False  False  False   
8   False  False  False  False  False  False  False  False  False  False   
9   False  False  False  False  False  False  False  False  False  False   
10  False  False  False  False  False  False  False  False  False  False   
11  False  False  False  False  False  False  False  False  False  False   
12  False  False  False  False  False  False  False  False  False  False   
13  False  False  False  False  False  False  False  False  False  False   
14  False  False  False  False  False  False  False  False  False  False   
15  False  False  False  False  False  False  False  False  False  False   
16  False  False  False  False  False  False  False  False  False  False   
17  False  False  False  False  False  False  False  False  False  False   
18  False  False  False  False  False  False  False  False  False  False   
19  False  False  False  False  False  False  False  False  False  False   
20  False  False  False  False  False  False  False  False  False  False   
21  False  False  False  False  False  False  False  False  False  False   
22  False  False  False  False  False  False  False  False  False  False   
23  False  False  False  False  False  False  False  False  False  False   
24  False  False  False  False  False  False  False  False  False  False   
25  False  False  False  False  False  False  False  False  False  False   
26  False  False  False  False  False  False  False  False  False  False   
27  False  False  False  False  False  False  False  False  False  False   
28  False  False  False  False  False  False  False  False  False  False   
29  False  False  False  False  False  False  False  False  False  False   
30  False  False  False  False  False  False  False  False  False  False   
31  False  False  False  False  False  False  False  False  False  False   

     carb  
0   False  
1   False  
2   False  
3   False  
4   False  
5   False  
6   False  
7   False  
8   False  
9   False  
10  False  
11  False  
12  False  
13  False  
14  False  
15  False  
16  False  
17  False  
18  False  
19  False  
20  False  
21  False  
22  False  
23  False  
24  False  
25  False  
26  False  
27  False  
28  False  
29  False  
30  False  
31  False

In [17]:
df.isna().sum()

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [18]:
df.min()

mpg     10.400
cyl      4.000
disp    71.100
hp      52.000
drat     2.760
wt       1.513
qsec    14.500
vs       0.000
am       0.000
gear     3.000
carb     1.000
dtype: float64

In [19]:
df.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [20]:
df.var()

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [21]:
df.quantile([0.25])

mpg  cyl     disp    hp  drat       wt     qsec   vs   am  gear  carb
0.25  15.425  4.0  120.825  96.5  3.08  2.58125  16.8925  0.0  0.0   3.0   2.0

In [22]:
df.vs.value_counts()

0    18
1    14
Name: vs, dtype: int64

In [23]:
df.gear.value_counts()

3    15
4    12
5     5
Name: gear, dtype: int64

# how to select specific column in data

In [24]:
#select only one column
df["mpg"]
df.mpg
df[["mpg"]]

mpg
0   21.0
1   21.0
2   22.8
3   21.4
4   18.7
5   18.1
6   14.3
7   24.4
8   22.8
9   19.2
10  17.8
11  16.4
12  17.3
13  15.2
14  10.4
15  10.4
16  14.7
17  32.4
18  30.4
19  33.9
20  21.5
21  15.5
22  15.2
23  13.3
24  19.2
25  27.3
26  26.0
27  30.4
28  15.8
29  19.7
30  15.0
31  21.4

In [25]:
#select multiple column
df[["mpg","gear"]]

mpg  gear
0   21.0     4
1   21.0     4
2   22.8     4
3   21.4     3
4   18.7     3
5   18.1     3
6   14.3     3
7   24.4     4
8   22.8     4
9   19.2     4
10  17.8     4
11  16.4     3
12  17.3     3
13  15.2     3
14  10.4     3
15  10.4     3
16  14.7     3
17  32.4     4
18  30.4     4
19  33.9     4
20  21.5     3
21  15.5     3
22  15.2     3
23  13.3     3
24  19.2     3
25  27.3     4
26  26.0     5
27  30.4     5
28  15.8     5
29  19.7     5
30  15.0     5
31  21.4     4

In [26]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

# loc/iloc

In [27]:
df.loc[[0,1,2],["mpg","cyl","disp","hp"]]

#if we have huge data then it is hard to write column names then iloc is use as index is use in iloc

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93

In [28]:
df.iloc[[0,1,2],[0,1,2,3]]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93

In [29]:
df.iloc[0:3,0:4]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93

In [30]:
df.loc[22:24,:]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2

In [31]:
df.iloc[22:24,:]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4

In [32]:

df.loc[[0,1,3],["mpg","cyl","hp"]]

mpg  cyl   hp
0  21.0    6  110
1  21.0    6  110
3  21.4    6  110

In [33]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [34]:
df.iloc[[0,1,2,4],0:4]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93
4  18.7    8  360.0  175

In [35]:
df.loc[22:24,["mpg","cyl","hp","gear"]]

mpg  cyl   hp  gear
22  15.2    8  150     3
23  13.3    8  245     3
24  19.2    8  175     3

In [36]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

# filter

In [37]:
df["gear"]==5

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27     True
28     True
29     True
30     True
31    False
Name: gear, dtype: bool

In [38]:
df[df["gear"]==5]

mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
26  26.0    4  120.3   91  4.43  2.140  16.7   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8

In [39]:
df[(df["gear"]==4 )& (df["mpg"]>22) & (df["wt"]>2)]

mpg  cyl   disp  hp  drat    wt   qsec  vs  am  gear  carb
2   22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1
7   24.4    4  146.7  62  3.69  3.19  20.00   1   0     4     2
8   22.8    4  140.8  95  3.92  3.15  22.90   1   0     4     2
17  32.4    4   78.7  66  4.08  2.20  19.47   1   1     4     1

In [40]:
df[(df["gear"]==4 ) | (df["mpg"]==3 )]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [41]:
df[(df["gear"]==4 )| (df["mpg"]>22) | (df["wt"]>2)]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

# Group by using pandas

In [42]:
df.groupby(["gear"])["mpg"].max()

gear
3    21.5
4    33.9
5    30.4
Name: mpg, dtype: float64

In [43]:
df.groupby(["gear","cyl"])["mpg"].mean()

gear  cyl
3     4      21.500
      6      19.750
      8      15.050
4     4      26.925
      6      19.750
5     4      28.200
      6      19.700
      8      15.400
Name: mpg, dtype: float64

In [44]:
df.groupby(["gear"])[["mpg"]].mean()

mpg
gear           
3     16.106667
4     24.533333
5     21.380000

In [45]:
df.groupby(["gear","cyl"])["mpg"].describe()

count    mean       std   min     25%    50%     75%   max
gear cyl                                                            
3    4      1.0  21.500       NaN  21.5  21.500  21.50  21.500  21.5
     6      2.0  19.750  2.333452  18.1  18.925  19.75  20.575  21.4
     8     12.0  15.050  2.774396  10.4  14.050  15.20  16.625  19.2
4    4      8.0  26.925  4.807360  21.4  22.800  25.85  30.900  33.9
     6      4.0  19.750  1.552417  17.8  18.850  20.10  21.000  21.0
5    4      2.0  28.200  3.111270  26.0  27.100  28.20  29.300  30.4
     6      1.0  19.700       NaN  19.7  19.700  19.70  19.700  19.7
     8      2.0  15.400  0.565685  15.0  15.200  15.40  15.600  15.8

In [46]:
pd.DataFrame([[1,2],[3,4]],columns=["a","b"],index=["a","b"])

# in python we can use same index as row and column

a  b
a  1  2
b  3  4

# How to add /del

In [47]:
df["new_col"]=1

In [48]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb  new_col
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4        1
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4        1
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1        1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1        1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2        1

In [49]:
#add a new column
l=[]
for i in df["mpg"]:
    if i>20:
        l.append("high")
    else:
        l.append("low")

df["new_col"]=l
df   

    

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb new_col
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4    high
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4    high
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1    high
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1    high
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2     low
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1     low
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4     low
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2    high
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2    high
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4     low
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4     low
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3     low
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3     low
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3     low
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4     low
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4     low
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4     low
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1    high
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2    high
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1    high
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1    high
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2     low
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2     low
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4     low
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2     low
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1    high
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2    high
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2    high
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4     low
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6     low
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8     low
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2    high

In [50]:
df["new_col"]=df["mpg"]>=22
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb  new_col
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4    False
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4    False
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1     True
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1    False
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2    False
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1    False
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4    False
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2     True
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2     True
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4    False
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4    False
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3    False
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3    False
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3    False
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4    False
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4    False
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4    False
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1     True
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2     True
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1     True
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1    False
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2    False
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2    False
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4    False
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2    False
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1     True
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2     True
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2     True
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4    False
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6    False
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8    False
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2    False

In [51]:

df.drop(["new_col"],axis=1,inplace=True)
#axis 0= row axis 1= column
#inplace= to save the value(to make the changes parmanent)

In [52]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [53]:
df.drop([0,1,2,7],axis=0)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [54]:

df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

# sorting of data 

In [55]:
df.sort_values(["hp"], ascending=[False])

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2

In [56]:
df.sort_values(["mpg","hp"], ascending=[True,False])

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1

# numpy intro

In [57]:
#numpy is a library in python used for working with arrays.it also has functions for working with matrices linear algebra
# & fourier transform.

In [58]:
import numpy as np
#pip install numpy
#!pip install numpy
#conda install numpy

In [59]:
l=[[1,2],
   [2,3]]

In [60]:
l+l

[[1, 2], [2, 3], [1, 2], [2, 3]]

In [61]:
a=np.array(l)
b=np.array([[4,5],
            [7,8]])

In [62]:
type(a)

numpy.ndarray

In [63]:
a.shape

(2, 2)

In [64]:
a

array([[1, 2],
       [2, 3]])

In [65]:
b

array([[4, 5],
       [7, 8]])

In [66]:
a+b

array([[ 5,  7],
       [ 9, 11]])

In [67]:
a**2

array([[1, 4],
       [4, 9]], dtype=int32)

In [68]:
b.T

array([[4, 7],
       [5, 8]])

In [69]:
a*b   #simple multiplication

array([[ 4, 10],
       [14, 24]])

In [70]:
np.dot(a,b)  #matrix multiplication

array([[18, 21],
       [29, 34]])

In [71]:
np.matmul(a,b)

array([[18, 21],
       [29, 34]])

In [72]:
ainv=np.linalg.inv(a)  #inverse of matrix

In [73]:
ainv

array([[-3.,  2.],
       [ 2., -1.]])

In [20]:
a

array([[1, 2],
       [2, 3]])

In [26]:
ainv

array([[-3.,  2.],
       [ 2., -1.]])

In [27]:
np.matmul(a,ainv)

array([[1., 0.],
       [0., 1.]])

In [29]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.sin(3.14/2)

0.9999996829318346

In [34]:
np.tan(22/7)

0.0012644899412945707

In [35]:
np.exp(2)

7.38905609893065

In [36]:
np.log(12)

2.4849066497880004

In [37]:
np.log10(10)

1.0

# index

In [38]:
a=[10,54,23,12,78,90,34]
#a=[start:end:step]

In [39]:
a[1:4]

[54, 23, 12]

In [40]:
a[1:]

[54, 23, 12, 78, 90, 34]

In [41]:
a[:4]

[10, 54, 23, 12]

In [42]:
a[1:4:1]

[54, 23, 12]

In [44]:
a[1:6:2]      #step size is 2

[54, 12, 90]

In [45]:
a[1:4:-1]

[]

In [46]:
a[4:1:-1]

[78, 12, 23]

In [70]:
def fun(s):
     if s==s[::-1]:
            return "true"
     else:
        return "false"


In [73]:
fun("mon")

'false'

In [74]:
fun("moom")

'true'

In [75]:
b

array([[4, 5],
       [7, 8]])

In [76]:
np.mean(b,axis=0)

array([5.5, 6.5])

In [77]:
np.mean(b,axis=1)

array([4.5, 7.5])

In [78]:
np.sum(b,axis=1)

array([ 9, 15])

In [80]:
b

array([[4, 5],
       [7, 8]])

In [81]:
np.median(b)

6.0

In [82]:
np.median(b,axis=1)

array([4.5, 7.5])

In [86]:
np.concatenate([b,b],axis=0)

array([[4, 5],
       [7, 8],
       [4, 5],
       [7, 8]])

In [87]:
np.concatenate([b,b],axis=1)

array([[4, 5, 4, 5],
       [7, 8, 7, 8]])